spring:
  application:
    name: crawler-zuul-gateway
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8050
  address: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka/
    enabled: true
  instance:
    hostname: ${server.address}


zuul:
  routes:
    main:
      path: /main/**
      service-id: crawler-backend
    captcha:
      path: /captcha/**
      service-id: captcha-service
  ignored-services: '*'

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000