spring:
  application:
    name: crawler-zuul-gateway
server:
  port: 8050
  address: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka/
    enabled: true #禁止作为eureka的客户端（如需要注册到eureka服务器，要设置为true）
  instance:
    hostname: ${server.address}

zuul:
  routes:
    main:
      path: /main/**
      service-id: crawler-backend
    captcha:
      path: /captcha/**
      service-id: captcha-service

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000