spring:
  application:
    name: crawler-mail
  mail:
    host: smtp.qq.com
    username: 110@qq.com
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka/
    enabled: true
  instance:
    hostname: ${server.address}

management:
  health:
    defaults:
      enabled: false
server:
  port: 8051
  address: 127.0.0.1
