crawler:
  md5Salt: crawler #密码加密salt
  defaultPassword: 123456 #用户默认密码
  captchaFtpServerHost: 192.168.1.120  # vsftpd-nginx默认host
  captchaFtpServerPort: 8888 # vsftpd-nginx默认port
  captchaFtpServerUserName: ftpuser # vsftpd默认用户名
  captchaFtpServerPassword: ftpuser # vsftpd默认密码
  captchaFtpServerUrl: /usr/local/img # vsftpd图片存放路径
  useEhCache: false #是否使用ehcache
  useCaptcha: false #是否使用验证码
  userTokenKey: crawler_key #用户token生成密钥
  useRedisCache: false #是否使用redis数据库缓存

spring:
  application:
    name: crawler-backend
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    username: 110@qq.com
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    database: 0
    host: 192.168.1.120
    port: 6379
    password: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    proxy-target-class: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
    enabled: false #禁止作为eureka的客户端（如需要注册到eureka服务器，要设置为true）

management:
  health:
    defaults:
      enabled: false

mybatis:
  mapperLocations: classpath:sqlmapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

flyway:
  baseline-on-migrate: true
  baseline-version: 1
  locations:
    classpath:db/migrations
  sql-migration-prefix: V
  sql-migration-suffix: .sql
  encoding: UTF-8

logging:
  config: classpath:logback-crawler.xml