crawler:
  md5Salt: crawler #密码加密salt
  defaultPassword: 123456 #用户默认密码
  useCaptcha: true #是否使用验证码
  userTokenKey: crawler_key #用户token生成密钥
  useEhCache: false #是否使用ehCache

spring:
  application:
    name: crawler-backend
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka/
    enabled: true #禁止作为eureka的客户端（如需要注册到eureka服务器，要设置为true）
  instance:
    hostname: ${server.address}

management:
  health:
    defaults:
      enabled: false

mybatis:
  mapperLocations: classpath:sqlmapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

flyway:
  baseline-on-migrate: true
  baseline-version: 1
  locations:
    classpath:db/migrations
  sql-migration-prefix: V
  sql-migration-suffix: .sql
  encoding: UTF-8

logging:
  config: classpath:logback-crawler.xml