crawler:
  md5Salt: crawler #密码加密salt
  defaultPassword: 123456 #用户默认密码
  captchaFtpServerHost: 192.168.3.129  # vsftpd-nginx默认host
  captchaFtpServerPort: 8888 # vsftpd-nginx默认port
  captchaFtpServerUserName: ftpuser # vsftpd默认用户名
  captchaFtpServerPassword: ftpuser # vsftpd默认密码
  captchaFtpServerUrl: /usr/local/img # vsftpd图片存放路径
  useEhCache: false #是否使用ehcache

spring:
  application:
    name: crawler
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    proxy-target-class: true
  mail:
        host: smtp.qq.com
        username: 110@qq.com
        password: 123456
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  redis:
    database: 0
    host: 192.168.3.129
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

logging:
  config: classpath:logback-crawler.xml

mybatis:
  mapperLocations: classpath:sqlmapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql