spring:
  application:
    name: crawler-redis-service-provider
  redis:
    database: 0
    host: 192.168.0.104
    port: 6379
    password: redis
    timeout: 10 #配置默认超时时间10ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka/
    enabled: true #禁止作为eureka的客户端（如需要注册到eureka服务器，要设置为true）
  instance:
    hostname: ${server.address}

management:
  health:
    defaults:
      enabled: false
server:
  address: 127.0.0.1
  port: 8099