spring:
  profiles:
    active: dev
  application:
    name: captcha-service
  zipkin:
    base-url: http://localhost:1006

logging:
  config: classpath:logback-captcha-producer.xml

management:
  health:
    defaults:
      enabled: true