crawler:
  captchaFtpServerHost: 192.168.1.120  # vsftpd-nginx默认host
  captchaFtpServerPort: 8888 # vsftpd-nginx默认port
  captchaFtpServerUserName: ftpuser # vsftpd默认用户名
  captchaFtpServerPassword: ftpuser # vsftpd默认密码
  captchaFtpServerUrl: /usr/local/img # vsftpd图片存放路径

spring:
  application:
    name: captcha-service
  redis:
    database: 0
    host: 192.168.1.120
    port: 6379
    password: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

server:
  port: 1001