crawler:
  captchaFtpServerHost: 192.168.1.120  # vsftpd-nginx默认host
  captchaFtpServerPort: 8888 # vsftpd-nginx默认port
  captchaFtpServerUserName: ftpuser # vsftpd默认用户名
  captchaFtpServerPassword: ftpuser # vsftpd默认密码
  captchaFtpServerUrl: /usr/local/img # vsftpd图片存放路径

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
    enabled: false #禁止作为eureka的客户端（如需要注册到eureka服务器，要设置为true）
  instance:
    hostname: ${server.address}
server:
  port: 1001
  address: 127.0.0.1