spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/crawler-plus/springcloud-config/
      label: master

server:
  port: 18888